[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "boomerang"
version = "0.1.0"
description = "Alerting engine built on Kontiki."
authors = ["Julien Weber <jpkwbr@protonmail.com>"]
readme = "README.md"
license = "Apache-2.0"
packages = [{ include = "boomerang" }]

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
kontiki = ">=1.2.0"
pydantic = "^2.0.0"
boomerang-contracts = { path = "packages/boomerang-contracts", develop = true }

[tool.poetry.group.dev.dependencies]
black = "^23.0.0"
isort = "^5.12.0"
flake8 = "^7.0.0"
behave = "^1.2.6"

[tool.poetry.scripts]
boomerang-subscription = "boomerang.services.subscription.main:run"
boomerang-email-notifier = "boomerang.services.notifiers.email.main:run"
boomerang-telegram-notifier = "boomerang.services.notifiers.telegram.main:run"
boomerang-alert-engine = "boomerang.services.alert_engine.main:run"
boomerang-earthquake-feed = "boomerang.services.alert_services.earthquake.main:run"
boomerang-demo-app = "boomerang.testing.demo_app.main:run"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["boomerang"]
